### ISSUE TITLE
Primary and Secondary Themes: Mobile

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#138]
I checked using the device emulator on Chrome Dev Tools and there are some discrepancies I'm seeing. Can you give mobile (and tablet) a quick pass?

Some issues I'm seeing:

- Left and right margins need to get reduced (content fills up more of the width)
- Some adjustments on the font-sizes for headlines for mobile. h1 goes down to 43px/47px. h2 and h3 goes down to 24px/28px.
- Image grids go to a single column layout for mobile portrait.

If it's helpful, check the mobile.css for mobile specific rules.

**Comment by mantasandri** [comment]
- Fixed with https://github.com/gettypubs/quire-starter-theme/commit/5e2416c2548e1dd6c8c3211dbe5d96d331c4eaf3 & https://github.com/gettypubs/quire-starter-theme/commit/d19b7ad9e4bcb004b98ef829138dfa7640a9ce1f
- Should be fixed with https://github.com/gettypubs/quire-starter-theme/commit/12d4e9cfd448c8048003ad8adc0214cae1d52537 & https://github.com/gettypubs/quire-starter-theme/commit/d19b7ad9e4bcb004b98ef829138dfa7640a9ce1f
- Fixed with https://github.com/gettypubs/quire-starter-theme/commit/6722fbb8b645dc5d9abaca3154ab9bbc8fbac5bd

Reuploaded for review, let me know how it look now.

**Comment by geealbers** [comment]
@rtapales Here's the link to the live demo site with all the latest and greatest stuff. if you could take a look at it on mobile and let us know if there is further work that should be done, that would be great. Thanks!

https://gettypubs.github.io/quire-starter/

**Comment by rtapales** [comment]
Thanks @geealbers. I should have time later this week.

**Comment by rtapales** [comment]
@geealbers I think I flagged key issues. Most seem pretty minor spacing and font-sizing discrepancies. I saw your note to update some content to represent Quire's full capabilities. Let me know if there's any specific items you want me to review once that's done.

**Comment by mantasandri** [comment]
I just put in a PR (https://github.com/gettypubs/quire-starter-theme/pull/42) that should fix all of the issues you put up.
