### ISSUE TITLE
Homepage: Edit Features list and determine images for slider

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#223]
5 images highlighting the most important/easy to illustrate features (my suggestions are: multiformat output, figure images & groups, video & audio embeds, dynamic navigation, page-level citation)

**Comment by geealbers** [comment]
Done with 8deb54e

I ended up with multiformat, multimedia, style customization, visual and scholarship optimized, and plain-text. Some of these were simply because I could think up images for them that were different enough looking from the other images. Happy for other ideas. Also the caption text I put is up for grabs. For one I wrote "scholar approved" which seems cheesy but was the only way I could think to say it. 

And I might try again on some of these images at some point. Not sure they all hold together cleanly.
