### ISSUE TITLE
Homepage: Suggest content to follow Quire Community section

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#224]
The website peters out after this section. What would we like to see here other than the illustrations?

**Comment by evale124** [comment]
I was browsing through some of the other websites we've been suggested and I noticed that most of them have social network site links, links to the main pages of the website, and a small contact form/subscribe form. At the moment we don't have social media sites but what do we think about the contact/subscribe form? I agree that the bottom is mostly empty graphics which is why I think some of these suggestions might work, perhaps not right away, but as the website builds.

**Comment by evale124** [comment]
I looked at the Arches, Netlify, and Hugo homepages. They all have different features, but I liked Hugo's testimonies section (use reviews in blocks). I thought it was interesting how Hugo has a box which states which systems their software works on (e.g. Mac, Windows, Linux) on the homepage. Would it help to include what systems Quire works with on the homepage?

**Comment by Erin-Cecele** [comment]
Yes, very good feedback. These are things Greg and I have been loosely discussing: potentially getting a twitter for Quire and adding a contact us form (seperate from the 'subscribe to mailing list' form). This is a good reminder for me to create open issues for these items!

**Comment by Erin-Cecele** [comment]
@evale124 Testimonies are definitely something we can build up over time. Good to know you responded well to them on Hugo's site. I noticed/liked Hugo's software system call out on their homepage, too. Right now, the operating systems are mentioned in the *expanded features & functionality* section in "What is Quire" as well as under "Implementation Considerations" in the docs. If we were to add that to the homepage where would you suggest placing that information?

**Comment by evale124** [comment]
I think it might look nice in place of the Stay in Touch (although this is debatable) if we could have the information as block images (like the block buttons you used under Discover Quire) with just a short description. And then right beneath it would be the Get Started button.

**Comment by Erin-Cecele** [comment]
When you say "the information as block images" do you mean: "contact us" / "Subscribe to newsletter" / "Check out events" / follow us on social media" something like that? or the Mac / PC / Linux note? Sorry, I'm crossing wires. You have so many great ideas. Really appreciate this feedback!

**Comment by evale124** [comment]
@Erin-Cecele Somewhere along the line, what do you think of replacing The Quire Community button/image with links/buttons/slider to work by the community (e.g. blog posts, projects, etc.), so kind of like a mini-showcase of the Community pages (when it is further developed)?
For reference, I was looking at Consonance homepage, specifically the section under Leveling up your publishing expertise.

**Comment by evale124** [comment]
> When you say "the information as block images" do you mean: "contact us" / "Subscribe to newsletter" / "Check out events" / follow us on social media" something like that? or the Mac / PC / Linux note? Sorry, I'm crossing wires. You have so many great ideas. Really appreciate this feedback!

Oh sorry, I meant the Mac/PC/Linux note. I think the social features of the homepage wouldn't be as cohesive together as placing the systems note right above the Get Started button. I think that putting the social features right above the Get Started button would not match the linear form of the homepage, but I do think it should be included on the homepage. Did I explain that better?

**Comment by Erin-Cecele** [comment]
That's an interesting idea. I think it would depend on how the community section of the website develops. Since we don't really have material to demonstrate that right now - other than user publication images which are already featured at the top. Maybe it could be some sort of reflection of the content on the Join Us page? (contribute to code, become an ambassador, Join the discussion, etc.)

**Comment by geealbers** [comment]
Done with 956d394

I thought ending the page with the two choices of either signing up for the mailing list, or signing up for the beta, was good. These are certainly the two main options we want everyone to choose between after scrolling the homepage. So I just rearranged the format using the features cards so that those two options stand side-by-side. It could maybe me more graphically punchy but I think it's fine enough as is. 

I'm going to look next at the idea of adding some small footer-like links as noted in issue #225
