### ISSUE TITLE
Crawl for broken links on website 

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#307]
Will require case-by-case fixes as well as global find and replace (possibly making use of regex.)

**Comment by geealbers** [comment]
Closed with #310 

@Erin-Cecele FYI, there were a bunch of internal links to the documentation where it still said `/guide/` instead of `/documentation/` but otherwise it was just a couple dozen random things that weren't resolving. Everything should be good now though, and I wend ahead and merged the changes in.
