### ISSUE TITLE
Page Bibliography Order Incorrect

### ISSUE THREAD

**Issue by swroberts** [gettypubs/quire#329]
When using integers in the `{{<q-cite "1">}}` shortcode for footnotes, the automatically added page bibliography orders the footnotes incorrectly when there are more than 9 references. It seems to sort using "short" as a string, resulting in: 1, 10, 2, 3, 4, etc.

The only option is to add a 0 before the integer, which results in: 01, 02, 03 [...] 09, 10, 11, etc. This is awkward.

This error makes it impossible to use standard footnote numbers for more than 9 footnotes.

Can the page bibliography sort function be adjust to sort as integers instead of strings? Or else try integer sorting before string?

**Comment by geealbers** [comment]
Hi @swroberts. We've been making some changes to the way `q-cite` works and they're not well documented yet, but I think I have a solution for you. You can use a `sort` value that will sort the notes in the order you'd expect, while still displaying the number as you'd like. 

```yaml
- id: "1"
  sort: "001"
  full: "Text of the footnote ..."
```
In this example I'm using `id` in place of `short`. Either will work but we're deprecating `short` and will be using `id` exclusively in the future. So `id` would be the number as you'd like it to actually display.

I'll also note here that we originally designed the `q-cite` shortcode to display [Author Date citations](https://en.wikipedia.org/wiki/Parenthetical_referencing#Author%E2%80%93date) rather than footnotes. And while `q-cite` can work for footnotes and adds the nice pop-up feature, the markup both for the footnote numbers in the text and for the list of footnotes at the bottom of the page are a little non-standard. For instance, the footnote numbers would normally be displayed in superscript and the footnotes themselves would be formatted as an HTML ordered list. You could adjust this with some CSS and/or some work in the templates themselves, or you could also skip the shortcode and use markdown-formatted footnotes. You can add markdown-formatted footnote numbers to the text list this:

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore 
et dolore magna aliqua. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum.[^1]
```

And at the bottom of the page, add a list of the notes with colons following the number syntax:

```markdown
[^1]: Text of the footnote ...

[^2]: Text of the second footnote ...
```
Hope this helps. Let us know if the `sort` worked for you, or if you end up using markdown instead.

**Comment by swroberts** [comment]
Hi Greg,
Thanks for the quick reply. Does q-cite map using id? I tried removing the short reference, but then receive the shortcode error for no short reference match when previewing. Adding a "sort" declaration doesn't seem to have any effect.

This is the cite shortcode: `{{<q-cite "7">}}`

This doesn't affect the order:
```
entries:
  - id: 7
    sort: "007"
    short: "7"
    full: "Test for seven."
  - id: 17
    sort: "017"
    short: "17"
    full: "Test for seventeen."
```

This doesn't work at all:
```
entries:
  - id: "7"
    sort: "007"
    full: "Test for seven."
  - id: "17"
    sort: "017"
    full: "Test for seventeen."
```
I should note I'm trying to use the page bibliography at the bottom of each page. Because that is automatic, there doesn't seem to be a way to tell it how to sort (as is an option in the q-bibliography shortcode).

I've also experimented with the Markdown footnote option, but because it automatically restarts numbering on each page, the footnotes don't translate well into the PDF version (multiple sets of footnotes beginning at 1).

**Comment by geealbers** [comment]
Oh. It's definitely possible I'm running a newer version of the q-cite shortcode than you have. Could you attach a copy of your `themes/quire-starter-theme/layouts/partials/page-bibliography.html` file? Or maybe better yet, try replacing it and your `themes/quire-starter-theme/layouts/shortcodes/q-cite.html` files with the attached versions.

[Archive.zip](https://github.com/gettypubs/quire/files/5668733/Archive.zip)

**Comment by swroberts** [comment]
Hi Greg! Thanks again! Swapping out those files has done the trick! It's actually more convenient to avoid short ref entirely and just add the sort ref.

Consider this issue resolved by updating the pertinent files!
