### ISSUE TITLE
Address cli and theme install warnings

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#55]
A number of varying dependency warnings come up in the command line when installing `quire-cli` and when running `quire install` (which runs the install process on `quire-starter-theme`). I believe all of them are dependencies of our dependencies, but our goal should be to pro-actively manage them, both for ourselves, and in documentation available to our users. I believe the steps to take are:

- [ ] Update the dependencies if possible
- [ ] Eliminate or substitute any dependencies that can be
- [ ] Document those that can't be easily updated or replaced
- [ ] Document the process for handling future warnings

---

**Sample install output from Mac:**

[theme-install-output--alpha12.txt](https://github.com/gettypubs/quire/files/2041126/theme-install-output--alpha12.txt)
[cli-install-output--alpha12.txt](https://github.com/gettypubs/quire/files/2041127/cli-install-output--alpha12.txt)

**Comment by geealbers** [comment]
See also issue #56

**Comment by naeluh** [comment]
I think most of these warnings/notices are gone in alpha-13 from these pull requests 

quire-starter-theme -> https://github.com/gettypubs/quire-starter-theme/pull/25, https://github.com/gettypubs/quire-starter-theme/pull/25

quire-cli -> https://github.com/gettypubs/quire-cli/pull/14

In terms of going forward and updating the packages for both projects:

**NPM Depreciation warnings:**

`npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

Depending on whether this is our dependency or a package we are using dependency will determine how we remove this. 

If it is in our project we need to update that package to the correct version.

dependency: `npm install --save package-name@version`
dev dependency: `npm install --save-dev package-name@version`

If it is in another project that we cannot update and it has not been updated. We must explicitly install the package into our package.json. We can do this by running the same command as above. Please note that this does not always work. If the dependency is listed in required than this temporary solution will not work. The process is to then fork the repository and fix the issue manually until the other repository has been updated or find a more up to date package that serves the same purpose.

dependency: `npm install --save package-name@version`
dev dependency: `npm install --save-dev package-name@version`

Using this command `npm --logevel=error install` will suppress some errors but not all. 

**NPM V8 Depreciation notices:**

```
../src/binding.cc:274:26: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        baton->callback->Call(1, argv);
                         ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:321:26: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        baton->callback->Call(2, argv);
                         ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
```

These notices will appear in various ways and are related to your node and npm versions. If you are using the latest version of node and npm more of these will appear. If you are using the stable LTS release there will be less.

Also these notices can be cause by differing versions of operating system. 

There is not a way of suppressing these notices other than fixing them or waiting for them to be fixed in their respective package, the only thing we can do is make recommendations for node and npm versions along with os versions. 

Using this command `npm --logevel=error install` will suppress some errors but not all. 

**NPM's new audit notices:**

In NPM they introduced an audit system that can tell you about vulnerable packages and various issues they might have. Similar to the github system but they used different criteria so these warnings/notices will be different. 

This will `found 225 vulnerabilities (201 low, 17 moderate, 6 high, 1 critical)` not appear in npm 5 and lower. 

These issues are dealt with by updating the package to the stable version, if the package is not updatable then a pull request to update the package must be made with the maintainer or the dependency must be explicitly installed in the package.json. If neither one of these work then a fork must be created with the fix in it. Otherwise these will not go away if using npm 6 or above. 

**Updating NPM packages:**

In terms of addressing these type of issues, I feel as though we can take the "address them as they appear" approach. 

The quire starter theme should be completely updated in alpha 13, quire cli on the other has some issues in it that are related to other projects and until we can either move that code out for something else or rewrite that portion of the code. 

This update does insure that code will be without notices/warnings for long and we will have to update/debug again.  

If a user posts an issue we can take a look. But some fixes can be easier than others irregardless of the package. If the syntax or api has changed it may require recoding which could take varied length of time.

In terms of documenting the dependencies, I think it would be beneficial to highlight some of the major dependencies with links to the package page and maybe a little info on how it is used, and then removing anything that is not in use. 

In quire-cli it installed 

`added 789 packages from 446 contributors and updated 1 package in 55.492s`

I think at the most we can document top level packages that are essential tot he project for an overview.

Also one other option is to change the way quire-cli is installed to have more control over the output of the install to command line. I am sure there are some options out here to explore. 

---

I can make a page of then top level dependencies for quire-cli and quire-starter-theme and we can add that to the docs, would that work? 

let me know if you have any questions or if I can clarify in any way.

Thanks!

**Comment by geealbers** [comment]
Hi @naeluh, thanks for this rundown! It all makes sense to me (mostly 😬) and I think if you can make a page top-level dependencies to add to the docs as you suggested, that would be great.

**Comment by naeluh** [comment]
Hey @geealbers thanks ! Yeah sorry I know that is a lot. Basically I think if we make sure to keep the packages up to date, it should prevent a lot of these types of warning and notices. 

Ok I will add a page to the docs. 

I think once we move the alpha 13 into place and I create doc page we can close these issues 
https://github.com/gettypubs/quire/issues/57
https://github.com/gettypubs/quire/issues/56
https://github.com/gettypubs/quire/issues/55

Let me know if you have any questions or if I can clarify in any way!

Thanks!
