### ISSUE TITLE
Consider replacement options for smoothState.js

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#72]
Quire currently uses [smoothState.js](https://github.com/miguel-perez/smoothState.js) to manage page transitions (both in request size and UX animation), but the library has now been inactive for a couple of years and is starting to cause some issues. See the discussion in https://github.com/gettypubs/quire-starter-theme/pull/24. [Turbolinks](https://github.com/turbolinks/turbolinks) is the primary option to replace smoothState, but others might be considered.

**Comment by workergnome** [comment]
I'm curious what the intent of using SmoothState is for your use case--is it just for the animation, or do you feel you actually need a strategy for loading pages quicker than a browser can refresh and load a static page?  It seems more fitting with your Quire methodology (as I understand it) to use native browser page loads, and not use a technique that introduces additional complexity and dependencies for minor performance improvements.

**Comment by geealbers** [comment]
I'd certainly agree with your take on Quire's methodology. I believe @egardner's primary goal with the use of smoothState was for animation and making for a nice reading ux, which along with structural simplicity/directness is also a key to what we want Quire to offer. Maybe Eric can weigh in more with his original intention, but you're right that if we replace smoothState, we should be careful to evaluate its replacement with an eye to not adding complexity, and making sure it really brings something useful to the table. Will be good to bring @rtapales into the conversation as well.

**Comment by naeluh** [comment]
That was my thought if this is the functionality (partial page loads and scrolling) than we don't need add an additional module for this. Also smoothstate uses jquery and I feel as though we can start moving away from that as a dependency.

**Comment by naeluh** [comment]
I am going to put a hold on this issue until we have quire-starter-theme is approved we may not need smoothState type functionality in the end. Let me know if there is any questions.

**Comment by naeluh** [comment]
If we still want a library to control state here are few alternatives:

barba.js -> https://github.com/luruke/barba.js 
swup -> https://github.com/gmrchk/swup

Either one of these could be a drop in replacement and they both do not use jquery and since we are using babel-preset-env most of the functions are now natively available that jquery would help with. 
Also I don't think we need a library for DOM manipulation. There are other options too but these projects seemed the most realized to me. If we want we can also opt to remove state management all together but I think its improves performance largely JS based projects.
